/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Game2048;

import my.mainmenu.MainMenu;

public class App {
    public static void main(String[] args) {
        MainMenu.main(args);
    }
}